name: release

on:
  release:
    types: [published]

jobs:
  generate-txt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 你可以根据需要选择 Python 版本
        
    - name: Generate rime zip
      run: |
        python others/release.py

    - name: Upload rime-schemas
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        asset_path: rime-chingjyu-pinyin-release.zip
        asset_name: rime-chingjyu-pinyin-release.zip
        asset_content_type: application/zip
        upload_url: ${{ github.event.release.upload_url }}